
server:
  port: 8000

spring:
  security:
    user:
      name: thatman-eureka
      password: miamoro1y-eureka

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: eureka-service
    prefer-ip-address: true
  server:
    enable-self-preservation: false


